<?php

// intentionally left blank, ready to receive module code
function csc_csv_import_views_post_execute($view) {
    if ($view->id() == 'csc_import_history_embedded_view') {

        $entries = $view->result;
        $filtered_entries = [];

        $quarters = [
            'Jan 1 - March 31' => 1,
            'April 1 - June 30' => 2,
            'July 1 - September 30' => 3,
            'October 1 - December 31' => 4,
        ];
        
        $newest_quarter = 0;
        $second_quarter = 0;

        foreach ($entries as $row) {
            $year = $row->_entity->get('csc_year_of_reporting')->getValue()[0]['numerator'];
            $quarter = $row->_entity->get('csc_month_of_reporting')->getValue()[0]['value'];
            $value = 10*$year + $quarters[$quarter];
            
            if ($value > $newest_quarter) {
                $second_quarter = $newest_quarter;
                $newest_quarter = $value;
            }
            elseif ($value > $second_quarter and $value != $newest_quarter) {
                $second_quarter = $value;
            }
        }

        foreach ($entries as $key => $row) {
            $year = $row->_entity->get('csc_year_of_reporting')->getValue()[0]['numerator'];
            $quarter = $row->_entity->get('csc_month_of_reporting')->getValue()[0]['value'];
            $value = 10*$year + $quarters[$quarter];
            
            if ($value != $newest_quarter and $value != $second_quarter) {
                unset ($view->result[$key]);
            }
        }

        $count = 0;
        foreach ($view->result as $key => $value) {
            if ($count >= 10) {
                unset ($view->result[$key]);
            }
            $count++;
        }
    }
}